# @package _global_

# seed: 100000
dataset_repo_id: gmm
dataset_root: 'data/gmm_unconditional_pref_cluster_0_negative_dataset_20251204_192929.npy'

wandb:
  enable: true
hydra:
  run:
    # Set `dir` to where you would like to save all of the run outputs. If you run another training session
    # with the same value for `dir` its contents will be overwritten unless you set `resume` to true.
    dir: data/maze2d_dp/outputs/${now:%Y.%m.%d}/${hydra.job.name}
  job:
    name: ${now:%H.%M.%S}_${env.name}_${policy.name}

device: "cuda:1"  # cpu

training:
  offline_steps: 100000
  online_steps: 0
  eval_freq: 0
  save_freq: 5000
  log_freq: 250
  save_checkpoint: true

  batch_size: 256
  grad_clip_norm: 10
  lr: 1.0e-4
  lr_scheduler: cosine
  lr_warmup_steps: 500
  adam_betas: [0.95, 0.999]
  adam_eps: 1.0e-8
  adam_weight_decay: 1.0e-6
  online_steps_between_rollouts: 1

  delta_timestamps: 
    observation.environment_state: "[0]"
    observation.state: "[0]"
    action: "[0]"

  # The original implementation doesn't sample frames for the last 7 steps,
  # which avoids excessive padding and leads to improved training results.
  drop_n_last_frames: false #7  # ${policy.horizon} - ${policy.n_action_steps} - ${policy.n_obs_steps} + 1
